name: DemoQ

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  autotests:
  
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test with pytest
        if: always()
        env:
            USER_NAME: ${{ secrets.USER_NAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: pytest -s -v --alluredir=allure-results
        continue-on-error: true
        
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Allure report 
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            allure_history: allure-history
            
      - name: Deploy report on GitHub page
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history
